### ISSUE TITLE
feature: example using path dependencies

### ISSUE THREAD

**Issue by tibbe** [astral-sh/uv-aws-lambda-example#3]
Even after days of trying I can't manage to create a Docker image with a multi-stage build that works for packages that use path dependencies. Here's an example package setup from a monorepo:

```
monorepo
├── service-a
├── service-b
├── library-a
└── library-b
```

Dependencies are as follows:
- `service-a` -> `library-a` and `library-b`
- `library-a` -> `library-b`
- `service-b` -> `library-b`

All dependencies use path dependencies e.g.

```toml
[project]
name = "service-a"
dependencies = [
    "library-a",
    "library-b",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
library-a = { path = "../library-a", editable = true }
library-b = { path = "../library-b", editable = true }
```

Any suggestions would be much appreciated.
